project_id = "jefpfwrwlcphqgphdbrj"

[functions.verifyPassword]
verify_jwt = false

[functions.getSignedUrl]
verify_jwt = false

[functions.createPasswordQR]
verify_jwt = false

[functions.redirect]
verify_jwt = false

[functions.bulkGenerate]
verify_jwt = false